# Enforce your MR | commit must follow best-practices: lint -> build -> test
name: Verify-Commit
run-name: Verify PR merge to ${{ github.base_ref }} by @${{ github.actor }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - main
      - 'releases/**'
  push:
    branches:
      - main
      - 'releases/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "verify"
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        # TO-DO: Find out why `npm ci` fails with: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Verify Lint
        run: npm run lint
      - name: Build package
        run: npm run build
      - name: Verify Unit test
        run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
